"""add user profile fields

Revision ID: 128021805369
Revises: ed3149df361c
Create Date: 2026-04-07 10:12:04.982332

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = '128021805369'
down_revision = 'ed3149df361c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    # ### end Alembic commands ###
