"""Adds comments table

Revision ID: 70a8bc679560
Revises: 836ea0414de1
Create Date: 2026-03-31 11:23:45.264602

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = '70a8bc679560'
down_revision = '836ea0414de1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
