"""add user profile fields

Revision ID: ed3149df361c
Revises: 70a8bc679560
Create Date: 2026-04-07 09:41:27.575188

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = 'ed3149df361c'
down_revision = '70a8bc679560'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=300), nullable=True))
    op.execute("UPDATE users SET username = email WHERE username IS NULL")
    op.alter_column('users', 'username', nullable=False)
    op.create_unique_constraint('uq_users_username', 'users', ['username'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
